config/routes.rb
Rails.application.routes.draw do
  resources :transaction_functions
  resources :data_functions
  resources :counts
  resources :projects
  resources :organizations
  devise_for :users
  resources :users

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/transaction_function.rb
class TransactionFunction < ApplicationRecord
end

app/controllers/transaction_functions_controller.rb
class TransactionFunctionsController < ApplicationController
  before_action :set_transaction_function, only: [:show, :edit, :update, :destroy]

  # GET /transaction_functions
  # GET /transaction_functions.json
  def index
    @transaction_functions = TransactionFunction.all
  end

  # GET /transaction_functions/1
  # GET /transaction_functions/1.json
  def show
  end

  # GET /transaction_functions/new
  def new
    @transaction_function = TransactionFunction.new
  end

  # GET /transaction_functions/1/edit
  def edit
  end

  # POST /transaction_functions
  # POST /transaction_functions.json
  def create
    @transaction_function = TransactionFunction.new(transaction_function_params)

    respond_to do |format|
      if @transaction_function.save
        format.html { redirect_to @transaction_function, notice: 'Transaction function was successfully created.' }
        format.json { render :show, status: :created, location: @transaction_function }
      else
        format.html { render :new }
        format.json { render json: @transaction_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_functions/1
  # PATCH/PUT /transaction_functions/1.json
  def update
    respond_to do |format|
      if @transaction_function.update(transaction_function_params)
        format.html { redirect_to @transaction_function, notice: 'Transaction function was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction_function }
      else
        format.html { render :edit }
        format.json { render json: @transaction_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_functions/1
  # DELETE /transaction_functions/1.json
  def destroy
    @transaction_function.destroy
    respond_to do |format|
      format.html { redirect_to transaction_functions_url, notice: 'Transaction function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_function
      @transaction_function = TransactionFunction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_function_params
      params.require(:transaction_function).permit(:requirement_name, :function, :kind, :qt_alr, :desc_alr, :qt_der, :desc_der, :obs)
    end
end

app/helpers/transaction_functions_helper.rb
module TransactionFunctionsHelper
end

app/views/transaction_functions/_form.html.erb
<%= form_for(transaction_function) do |f| %>
  <% if transaction_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction_function.errors.count, "error") %> prohibited this transaction_function from being saved:</h2>

      <ul>
      <% transaction_function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requirement_name %>
    <%= f.text_field :requirement_name %>
  </div>

  <div class="field">
    <%= f.label :function %>
    <%= f.text_field :function %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.text_field :kind %>
  </div>

  <div class="field">
    <%= f.label :qt_alr %>
    <%= f.number_field :qt_alr %>
  </div>

  <div class="field">
    <%= f.label :desc_alr %>
    <%= f.text_area :desc_alr %>
  </div>

  <div class="field">
    <%= f.label :qt_der %>
    <%= f.number_field :qt_der %>
  </div>

  <div class="field">
    <%= f.label :desc_der %>
    <%= f.text_area :desc_der %>
  </div>

  <div class="field">
    <%= f.label :obs %>
    <%= f.text_area :obs %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transaction_functions/edit.html.erb
<h1>Editing Transaction Function</h1>

<%= render 'form', transaction_function: @transaction_function %>

<%= link_to 'Show', @transaction_function %> |
<%= link_to 'Back', transaction_functions_path %>

app/views/transaction_functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transaction Functions</h1>

<table>
  <thead>
    <tr>
      <th>Requirement name</th>
      <th>Function</th>
      <th>Kind</th>
      <th>Qt alr</th>
      <th>Desc alr</th>
      <th>Qt der</th>
      <th>Desc der</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_functions.each do |transaction_function| %>
      <tr>
        <td><%= transaction_function.requirement_name %></td>
        <td><%= transaction_function.function %></td>
        <td><%= transaction_function.kind %></td>
        <td><%= transaction_function.qt_alr %></td>
        <td><%= transaction_function.desc_alr %></td>
        <td><%= transaction_function.qt_der %></td>
        <td><%= transaction_function.desc_der %></td>
        <td><%= transaction_function.obs %></td>
        <td><%= link_to 'Show', transaction_function %></td>
        <td><%= link_to 'Edit', edit_transaction_function_path(transaction_function) %></td>
        <td><%= link_to 'Destroy', transaction_function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction Function', new_transaction_function_path %>

app/views/transaction_functions/new.html.erb
<h1>New Transaction Function</h1>

<%= render 'form', transaction_function: @transaction_function %>

<%= link_to 'Back', transaction_functions_path %>

app/views/transaction_functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requirement name:</strong>
  <%= @transaction_function.requirement_name %>
</p>

<p>
  <strong>Function:</strong>
  <%= @transaction_function.function %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @transaction_function.kind %>
</p>

<p>
  <strong>Qt alr:</strong>
  <%= @transaction_function.qt_alr %>
</p>

<p>
  <strong>Desc alr:</strong>
  <%= @transaction_function.desc_alr %>
</p>

<p>
  <strong>Qt der:</strong>
  <%= @transaction_function.qt_der %>
</p>

<p>
  <strong>Desc der:</strong>
  <%= @transaction_function.desc_der %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @transaction_function.obs %>
</p>

<%= link_to 'Edit', edit_transaction_function_path(@transaction_function) %> |
<%= link_to 'Back', transaction_functions_path %>