config/routes.rb
Rails.application.routes.draw do
  resources :transaction_functions
  resources :data_functions
  resources :counts
  resources :projects
  resources :organizations
  devise_for :users
  resources :users

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_function.rb
class DataFunction < ApplicationRecord
end

app/controllers/data_functions_controller.rb
class DataFunctionsController < ApplicationController
  before_action :set_data_function, only: [:show, :edit, :update, :destroy]

  # GET /data_functions
  # GET /data_functions.json
  def index
    @data_functions = DataFunction.all
  end

  # GET /data_functions/1
  # GET /data_functions/1.json
  def show
  end

  # GET /data_functions/new
  def new
    @data_function = DataFunction.new
  end

  # GET /data_functions/1/edit
  def edit
  end

  # POST /data_functions
  # POST /data_functions.json
  def create
    @data_function = DataFunction.new(data_function_params)

    respond_to do |format|
      if @data_function.save
        format.html { redirect_to @data_function, notice: 'Data function was successfully created.' }
        format.json { render :show, status: :created, location: @data_function }
      else
        format.html { render :new }
        format.json { render json: @data_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_functions/1
  # PATCH/PUT /data_functions/1.json
  def update
    respond_to do |format|
      if @data_function.update(data_function_params)
        format.html { redirect_to @data_function, notice: 'Data function was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_function }
      else
        format.html { render :edit }
        format.json { render json: @data_function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_functions/1
  # DELETE /data_functions/1.json
  def destroy
    @data_function.destroy
    respond_to do |format|
      format.html { redirect_to data_functions_url, notice: 'Data function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_function
      @data_function = DataFunction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_function_params
      params.require(:data_function).permit(:requirement_name, :function, :kind, :qt_rlr, :desc_rlr, :qt_der, :desc_der, :obs)
    end
end

app/helpers/data_functions_helper.rb
module DataFunctionsHelper
end

app/views/data_functions/_form.html.erb
<%= form_for(data_function) do |f| %>
  <% if data_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_function.errors.count, "error") %> prohibited this data_function from being saved:</h2>

      <ul>
      <% data_function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requirement_name %>
    <%= f.text_field :requirement_name %>
  </div>

  <div class="field">
    <%= f.label :function %>
    <%= f.text_field :function %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.text_field :kind %>
  </div>

  <div class="field">
    <%= f.label :qt_rlr %>
    <%= f.number_field :qt_rlr %>
  </div>

  <div class="field">
    <%= f.label :desc_rlr %>
    <%= f.text_area :desc_rlr %>
  </div>

  <div class="field">
    <%= f.label :qt_der %>
    <%= f.number_field :qt_der %>
  </div>

  <div class="field">
    <%= f.label :desc_der %>
    <%= f.text_area :desc_der %>
  </div>

  <div class="field">
    <%= f.label :obs %>
    <%= f.text_area :obs %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_functions/edit.html.erb
<h1>Editing Data Function</h1>

<%= render 'form', data_function: @data_function %>

<%= link_to 'Show', @data_function %> |
<%= link_to 'Back', data_functions_path %>

app/views/data_functions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Functions</h1>

<table>
  <thead>
    <tr>
      <th>Requirement name</th>
      <th>Function</th>
      <th>Kind</th>
      <th>Qt rlr</th>
      <th>Desc rlr</th>
      <th>Qt der</th>
      <th>Desc der</th>
      <th>Obs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_functions.each do |data_function| %>
      <tr>
        <td><%= data_function.requirement_name %></td>
        <td><%= data_function.function %></td>
        <td><%= data_function.kind %></td>
        <td><%= data_function.qt_rlr %></td>
        <td><%= data_function.desc_rlr %></td>
        <td><%= data_function.qt_der %></td>
        <td><%= data_function.desc_der %></td>
        <td><%= data_function.obs %></td>
        <td><%= link_to 'Show', data_function %></td>
        <td><%= link_to 'Edit', edit_data_function_path(data_function) %></td>
        <td><%= link_to 'Destroy', data_function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Function', new_data_function_path %>

app/views/data_functions/new.html.erb
<h1>New Data Function</h1>

<%= render 'form', data_function: @data_function %>

<%= link_to 'Back', data_functions_path %>

app/views/data_functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requirement name:</strong>
  <%= @data_function.requirement_name %>
</p>

<p>
  <strong>Function:</strong>
  <%= @data_function.function %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @data_function.kind %>
</p>

<p>
  <strong>Qt rlr:</strong>
  <%= @data_function.qt_rlr %>
</p>

<p>
  <strong>Desc rlr:</strong>
  <%= @data_function.desc_rlr %>
</p>

<p>
  <strong>Qt der:</strong>
  <%= @data_function.qt_der %>
</p>

<p>
  <strong>Desc der:</strong>
  <%= @data_function.desc_der %>
</p>

<p>
  <strong>Obs:</strong>
  <%= @data_function.obs %>
</p>

<%= link_to 'Edit', edit_data_function_path(@data_function) %> |
<%= link_to 'Back', data_functions_path %>