config/routes.rb
Rails.application.routes.draw do
  resources :transaction_functions
  resources :data_functions
  resources :counts
  resources :projects
  resources :organizations
  devise_for :users
  resources :users

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/count.rb
class Count < ApplicationRecord
  belongs_to :project
  has_many :data_functions
  has_many :transaction_functions

end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
  before_action :set_count, only: [:show, :edit, :update, :destroy]

  # GET /counts
  # GET /counts.json
  def index
    @counts = Count.all
  end

  # GET /counts/1
  # GET /counts/1.json
  def show
    result_data = []
    result_transaction = []
    @project = Project.find(params[:id])
    @count = Count.find(params[:id])
    @data_functions = @count.data_functions
    @transaction_functions = @count.transaction_functions

  #set complexity of data functions
    @data_functions.each do |data|
      if (data.qt_rlr <= 1 && data.qt_der < 50) || (data.qt_rlr.between?(2,5) && data.qt_der < 20)
        complexity = 'baixa'
      elsif (data.qt_rlr <= 1 && data.qt_der > 50) || (data.qt_rlr.between?(2,5) && qt_der.between?(20,50)) || (qt_rlr > 5 && qt_der < 20)
        complexity = 'media'
      else
        complexity = 'alta'
      end

  #set value for complexity
      if complexity == 'baixa' && data.kind == 'ali'
        value = 7
        result_data << value
      elsif complexity == 'media' && data.kind =='ali'
        value = 10
        result_data << value
      elsif complexity == 'alta' && data.kind == 'ali'
        value = 15
        result_data << value
      elsif complexity == 'baixa' && data.kind == 'aie'
        value = 5
        result_data << value
      elsif complexity == 'media' && data.kind = 'aie'
        value = 7
        result_data << value
      else
        value = 10
        result_data << value
      end
    end

  @transaction_functions.each do |transaction|
      if transaction.kind == 'ee'
        if (transaction.qt_alr < 2 && transaction.qt_der < 5) || (transaction.qt_alr < 2 && transaction.qt_der.between?(5,15)) ||
           (transaction.qt_alr == 2 && transaction.qt_der.between?(5,15))
            complexity = 'baixa'
        elsif (transaction.qt_alr < 2 && transaction.qt_der > 15) || (transaction.qt_alr == 2 && transaction.qt_der.between?(5,15)) ||
              (transaction.qt_alr > 2 && transaction.qt_der < 5)
                complexity = 'media'
        else
          complexity = 'alta'
        end
      else
        if (transaction.qt_alr < 2 && transaction.qr_der < 6) || (transaction.qt_alr < 2 && transaction.qr_der.between?(6,19)) ||
          (transaction.qt_alr.between?(2,3) && transaction.qt_alr < 6)
          complexity= 'baixa'
        elsif (transaction.qt_alr < 2 && transaction.qr_der > 19) || (transaction.qt_alr.between?(2,3) && transaction.qr_der.between?(6,19)) ||
          (transaction.qt_alr > 3 && transaction.qt_alr < 6)
          complexity = 'media'
        else
          complexity = 'alta'
        end
      end
      if complexity == 'baixa' && (transaction.kind == 'ee' || transaction.kind == 'ce')
        value = 3
        result_transaction << value
      elsif complexity == 'media' && (transaction.kind == 'ee' || transaction.kind == 'ce')
        value = 4
        result_transaction << value
      elsif complexity == 'alta' && (transaction.kind == 'ee' || transaction.kind == 'ce')
        value = 6
        result_transaction << value
      elsif complexity == 'baixa' && transaction.kind == 'se'
        value = 4
        result_transaction << value
      elsif complexity == 'media' && transaction.kind == 'se'
        value = 5
        result_transaction << value
      else
        value = 7
        result_transaction << value
      end

    end
    result_total = []
    result_total = result_transaction + result_data
    result_final = result_total.inject(:+)
    cost = result_final*@count.point_cost
    @project.update_attributes(cost: cost)
    @project.save
    @count.update_attributes(result: result_final)
    @count.save
  end

  # GET /counts/new
  def new
    @count = Count.new
  end

  # GET /counts/1/edit
  def edit
  end

  # POST /counts
  # POST /counts.json
  def create
    @count = Count.new(count_params)

    respond_to do |format|
      if @count.save
        format.html { redirect_to @count, notice: 'Count was successfully created.' }
        format.json { render :show, status: :created, location: @count }
      else
        format.html { render :new }
        format.json { render json: @count.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counts/1
  # PATCH/PUT /counts/1.json
  def update
    respond_to do |format|
      if @count.update(count_params)
        format.html { redirect_to @count, notice: 'Count was successfully updated.' }
        format.json { render :show, status: :ok, location: @count }
      else
        format.html { render :edit }
        format.json { render json: @count.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counts/1
  # DELETE /counts/1.json
  def destroy
    @count.destroy
    respond_to do |format|
      format.html { redirect_to counts_url, notice: 'Count was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_count
      @count = Count.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def count_params
      params.require(:count).permit(:count_date, :result, :style, :pattern, :point_cost, :baseline)
    end

    def transaction_function_params
      params.require(:transaction_function).permit(:requirement_name, :function, :kind, :qt_alr, :desc_alr, :qt_der, :desc_der, :obs)
    end

    def data_function_params
      params.require(:data_function).permit(:requirement_name, :function, :kind, :qt_rlr, :desc_rlr, :qt_der, :desc_der, :obs)
    end
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/views/counts/_form.html.erb
<%= form_for(count) do |f| %>
  <% if count.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(count.errors.count, "error") %> prohibited this count from being saved:</h2>

      <ul>
      <% count.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :count_date %>
    <%= f.date_select :count_date %>
  </div>

  <div class="field">
    <%= f.label :result %>
    <%= f.number_field :result %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counts/edit.html.erb
<h1>Editing Count</h1>

<%= render 'form', count: @count %>

<%= link_to 'Show', @count %> |
<%= link_to 'Back', counts_path %>

app/views/counts/index.html.erb
<h1>Counts</h1>

<table>
  <thead>
    <tr>
      <th>Count date</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counts.each do |count| %>
      <tr>
        <td><%= count.count_date %></td>
        <td><%= count.result %></td>
        <td><%= link_to 'Show', count %></td>
        <td><%= link_to 'Edit', edit_count_path(count) %></td>
        <td><%= link_to 'Destroy', count, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Count', new_count_path %>

app/views/counts/new.html.erb
<h1>New Count</h1>

<%= render 'form', count: @count %>

<%= link_to 'Back', counts_path %>

app/views/counts/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#info" data-toggle="tab" aria-expanded="true">Informações</a>
          </li>
          <li class="">
            <a href="#func_data" data-toggle="tab" aria-expanded="false">Funções de Dados</a>
          </li>
          <li class="">
            <a href="#func_tran" data-toggle="tab" aria-expanded="false">Funções de Transação</a>
          </li>
          <li class="">
            <a href="#resumo" data-toggle="tab" aria-expanded="false">Resumo</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane fade active in" id="info">
            <p>
              <strong>Data da Contagem:</strong>
              <%= @count.count_date %>
            </p>
            <p>
              <strong>Resultado:</strong>
              <%= @count.result %>
            </p>
          </div>
          <div class="tab-pane fade" id="func_data">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="table-resposive">
                  <table class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Nome Requisito</th>
                        <th>Nome Função</th>
                        <th>Tipo</th>
                        <th>Qt. RLR</th>
                        <th>Desc. RLR</th>
                        <th>Qt. DER</th>
                        <th>Desc. DER</th>
                        <th>Observações</th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @data_functions.each do |data_function| %>
                      <tr>
                        <td><%= data_function.requirement_name %></td>
                        <td><%= data_function.function %>
                        </td>
                        <td><%= data_function.kind %></td>
                        <td><%= data_function.qt_rlr %></td>
                        <td><%= data_function.desc_rlr %></td>
                        <td><%= data_function.qt_der %></td>
                        <td><%= data_function.desc_der %></td>
                        <td><%= data_function.obs %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="func_tran">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="table-resposive">
                  <table class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Nome Requisito</th>
                        <th>Nome Função</th>
                        <th>Tipo</th>
                        <th>Qt. RLR</th>
                        <th>Desc. RLR</th>
                        <th>Qt. DER</th>
                        <th>Desc. DER</th>
                        <th>Observações</th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @transaction_functions.each do |transaction_function| %>
                      <tr>
                        <td><%= transaction_function.requirement_name %></td>
                        <td><%= transaction_function.function %>
                        </td>
                        <td><%= transaction_function.kind %></td>
                        <td><%= transaction_function.qt_alr %></td>
                        <td><%= transaction_function.desc_alr %></td>
                        <td><%= transaction_function.qt_der %></td>
                        <td><%= transaction_function.desc_der %></td>
                        <td><%= transaction_function.obs %></td>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="resumo">
            oieiuoeiou 3
          </div>
        </div>
      </div>
    </div>
  </div>
</div>