config/routes.rb
Rails.application.routes.draw do
  resources :transaction_functions
  resources :data_functions
  resources :counts
  resources :projects
  resources :organizations
  devise_for :users
  resources :users

  devise_scope :user do
    authenticated :user do
      root 'projects#index'
end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :adress, :phone)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adress %>
    <%= f.text_field :adress %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1 class="page-header">Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adress</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.adress %></td>
        <td><%= organization.phone %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @organization.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>